import { Prisma } from "@/generated/prisma";

export const AUDIT_ACTIONS = {
  // Phase Transitions
  ACTIVATE_PHASE: "ACTIVATE_PHASE",
  SUBMIT_FOR_INTERNAL_REVIEW: "SUBMIT_FOR_INTERNAL_REVIEW",
  APPROVE_INTERNAL: "APPROVE_INTERNAL",
  SUBMIT_FOR_CLIENT_REVIEW: "SUBMIT_FOR_CLIENT_REVIEW",
  APPROVE_CLIENT_PHASE: "APPROVE_CLIENT_PHASE",
  REJECT_PHASE_INTERNAL: "REJECT_PHASE_INTERNAL",
  REJECT_PHASE_CLIENT: "REJECT_PHASE_CLIENT",
  REOPEN_PHASE: "REOPEN_PHASE",
  COMPLETE_SUPERVISION_PHASE: "COMPLETE_SUPERVISION_PHASE",
  REVISION_OVERRIDE_ADMIN: "REVISION_OVERRIDE_ADMIN",
  BYPASS_PHASE_TO_COMPLETED: "BYPASS_PHASE_TO_COMPLETED",

  // Project Operations
  BOOTSTRAP_PROJECT: "BOOTSTRAP_PROJECT",
  UPDATE_PROJECT_METADATA: "UPDATE_PROJECT_METADATA",
  UPDATE_PROJECT_PRIORITY: "UPDATE_PROJECT_PRIORITY",
  SYNC_PROJECT_CHECKLISTS: "SYNC_PROJECT_CHECKLISTS",
  DELETE_PROJECT: "DELETE_PROJECT",
  PROJECT_COMPLETED_MANUAL: "PROJECT_COMPLETED_MANUAL",

  // Content Mutations
  CREATE_CD_ITEM: "CREATE_CD_ITEM",
  UPDATE_CD_ITEM: "UPDATE_CD_ITEM",
  UPDATE_CD_STATUS: "UPDATE_CD_STATUS",
  DELETE_CD_ITEM: "DELETE_CD_ITEM",
  ADD_ACTIVITY: "ADD_ACTIVITY",
  UPDATE_ACTIVITY_CONTENT: "UPDATE_ACTIVITY_CONTENT",
  UPDATE_ACTIVITY_DUE_DATE: "UPDATE_ACTIVITY_DUE_DATE",
  TOGGLE_ACTIVITY_STATUS: "TOGGLE_ACTIVITY_STATUS",
  DELETE_ACTIVITY: "DELETE_ACTIVITY",
  ADD_DELIVERABLE: "ADD_DELIVERABLE",
  TOGGLE_CHECKLIST: "TOGGLE_CHECKLIST",
  ADD_CHECKLIST_ITEM: "ADD_CHECKLIST_ITEM",
  UPDATE_CHECKLIST_ITEM: "UPDATE_CHECKLIST_ITEM",
  DELETE_CHECKLIST_ITEM: "DELETE_CHECKLIST_ITEM",
  DETACH_CHECKLIST_TEMPLATE: "DETACH_CHECKLIST_TEMPLATE",
  REORDER_CHECKLIST: "REORDER_CHECKLIST",
  ACTIVITY_CONVERTED_FEEDBACK_TO_TODO: "ACTIVITY_CONVERTED_FEEDBACK_TO_TODO",

  // System
  UNDO_TRIGGER: "UNDO_TRIGGER",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",

  // Library & extensions
  LIBRARY_CREATE_VENDOR: "LIBRARY_CREATE_VENDOR",
  LIBRARY_UPDATE_VENDOR: "LIBRARY_UPDATE_VENDOR",
  LIBRARY_DELETE_VENDOR: "LIBRARY_DELETE_VENDOR",
  CATALOG_CREATE: "CATALOG_CREATE",
  CATALOG_UPDATE: "CATALOG_UPDATE",
  CATALOG_DELETE: "CATALOG_DELETE",
  LIBRARY_CREATE_REQUEST: "LIBRARY_CREATE_REQUEST",
  LIBRARY_UPDATE_REQUEST_STATUS: "LIBRARY_UPDATE_REQUEST_STATUS",
  LIBRARY_DELETE_REQUEST: "LIBRARY_DELETE_REQUEST",
  LIBRARY_CREATE_PROMOTION_REQUEST: "LIBRARY_CREATE_PROMOTION_REQUEST",
  LIBRARY_APPROVE_PROMOTION: "LIBRARY_APPROVE_PROMOTION",
  LIBRARY_REJECT_PROMOTION: "LIBRARY_REJECT_PROMOTION",
  MASTERDATA_MATERIAL_CANDIDATE_UPDATE:
    "MASTERDATA_MATERIAL_CANDIDATE_UPDATE",
  MASTERDATA_MATERIAL_CANDIDATE_DISMISS:
    "MASTERDATA_MATERIAL_CANDIDATE_DISMISS",
  MASTERDATA_MATERIAL_CANDIDATE_REOPEN:
    "MASTERDATA_MATERIAL_CANDIDATE_REOPEN",
  MASTERDATA_MATERIAL_CANDIDATE_PROMOTE:
    "MASTERDATA_MATERIAL_CANDIDATE_PROMOTE",
  MASTERDATA_SAMPLE_CANDIDATE_UPDATE: "MASTERDATA_SAMPLE_CANDIDATE_UPDATE",
  MASTERDATA_SAMPLE_CANDIDATE_DISMISS: "MASTERDATA_SAMPLE_CANDIDATE_DISMISS",
  MASTERDATA_SAMPLE_CANDIDATE_REOPEN: "MASTERDATA_SAMPLE_CANDIDATE_REOPEN",
  MASTERDATA_SAMPLE_CANDIDATE_PROMOTE: "MASTERDATA_SAMPLE_CANDIDATE_PROMOTE",

  // R9 — sample request follow-up, worked from Master Data.
  MASTERDATA_REQUEST_VENDOR_FOLLOWUP: "MASTERDATA_REQUEST_VENDOR_FOLLOWUP",
  MASTERDATA_REQUEST_RECEIVE: "MASTERDATA_REQUEST_RECEIVE",
  MASTERDATA_REQUEST_UNAVAILABLE: "MASTERDATA_REQUEST_UNAVAILABLE",
  MASTERDATA_REQUEST_REOPEN: "MASTERDATA_REQUEST_REOPEN",

  // R12 — physical sample library (the office shelf).
  MASTERDATA_SAMPLE_CREATE: "MASTERDATA_SAMPLE_CREATE",
  MASTERDATA_SAMPLE_UPDATE: "MASTERDATA_SAMPLE_UPDATE",
  MASTERDATA_SAMPLE_STATUS: "MASTERDATA_SAMPLE_STATUS",

  // Client Operations
  CLIENT_DELETE: "CLIENT_DELETE",
  CLIENT_MERGE: "CLIENT_MERGE",
  CLIENT_UPDATE_BRANDING: "CLIENT_UPDATE_BRANDING",

  // Settings & Configuration
  UPDATE_SYSTEM_CONFIG: "UPDATE_SYSTEM_CONFIG",
  UPDATE_TIMELINE_TEMPLATE: "UPDATE_TIMELINE_TEMPLATE",
  CREATE_CHECKLIST_TEMPLATE: "CREATE_CHECKLIST_TEMPLATE",
  DELETE_CHECKLIST_TEMPLATE: "DELETE_CHECKLIST_TEMPLATE",
  UPSERT_SCHEDULE_CATEGORY_CONFIG: "UPSERT_SCHEDULE_CATEGORY_CONFIG",
  DELETE_SCHEDULE_CATEGORY_CONFIG: "DELETE_SCHEDULE_CATEGORY_CONFIG",

  // User & Access Control
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",
  
  // content mutations
  DEFER_ACTIVITY: "DEFER_ACTIVITY",

  // Extension: Scheduler Pillar 2
  SCHEDULE_CREATE_ENTRY: "SCHEDULE_CREATE_ENTRY",
  SCHEDULE_DELETE_ENTRY: "SCHEDULE_DELETE_ENTRY",
  SCHEDULE_ADD_OPTION: "SCHEDULE_ADD_OPTION",
  SCHEDULE_APPROVE_OPTION: "SCHEDULE_APPROVE_OPTION",
  SCHEDULE_UPDATE_ENTRY: "SCHEDULE_UPDATE_ENTRY",
  SCHEDULE_REORDER: "SCHEDULE_REORDER",
  SCHEDULE_PROMOTE_TO_LIBRARY: "SCHEDULE_PROMOTE_TO_LIBRARY",
  SCHEDULE_UPDATE_SNAPSHOT: "SCHEDULE_UPDATE_SNAPSHOT",
  SCHEDULE_DELETE_OPTION: "SCHEDULE_DELETE_OPTION",
  SCHEDULE_EXPORT: "SCHEDULE_EXPORT",
  SCHEDULE_IMPORT: "SCHEDULE_IMPORT",
  SCHEDULE_SWITCH_OPTION: "SCHEDULE_SWITCH_OPTION",
  SCHEDULE_MERGE_CATEGORIES: "SCHEDULE_MERGE_CATEGORIES",
  CATALOG_SYNC_PROPAGATED: "CATALOG_SYNC_PROPAGATED",
  LIBRARY_MERGE_VENDOR: "LIBRARY_MERGE_VENDOR",
  SCHEDULE_SWAP_ENTRIES: "SCHEDULE_SWAP_ENTRIES",
  SCHEDULE_APPLY_TEMPLATE: "SCHEDULE_APPLY_TEMPLATE",
  SET_SCHEDULE_TEMPLATE_DEFAULT_ENTRY: "SET_SCHEDULE_TEMPLATE_DEFAULT_ENTRY",
  RENDER_BOARD_CREATE: "RENDER_BOARD_CREATE",
  RENDER_BOARD_UPDATE: "RENDER_BOARD_UPDATE",
  RENDER_BOARD_DELETE: "RENDER_BOARD_DELETE",
  RENDER_ANNOTATION_CREATE: "RENDER_ANNOTATION_CREATE",
  RENDER_ANNOTATION_UPDATE: "RENDER_ANNOTATION_UPDATE",
  RENDER_ANNOTATION_DELETE: "RENDER_ANNOTATION_DELETE",

  // Extension: SketchUp material code management
  SKETCHUP_QUEUE_MATERIAL_MERGE: "SKETCHUP_QUEUE_MATERIAL_MERGE",
  SKETCHUP_SET_MATERIAL_RESERVED: "SKETCHUP_SET_MATERIAL_RESERVED",
  SKETCHUP_NORMALIZE_MATERIAL_CODES: "SKETCHUP_NORMALIZE_MATERIAL_CODES",
  SKETCHUP_UPDATE_CATALOG_ITEM: "SKETCHUP_UPDATE_CATALOG_ITEM",

  // Extension: MOM
  MOM_CREATE_DOCUMENT: "MOM_CREATE_DOCUMENT",
  MOM_UPDATE_DOCUMENT: "MOM_UPDATE_DOCUMENT",
  MOM_DELETE_DOCUMENT: "MOM_DELETE_DOCUMENT",
  MOM_CREATE_ITEM: "MOM_CREATE_ITEM",
  MOM_UPDATE_ITEM: "MOM_UPDATE_ITEM",
  MOM_DELETE_ITEM: "MOM_DELETE_ITEM",
  MOM_REORDER_ITEM: "MOM_REORDER_ITEM",
  MOM_UPLOAD_IMAGE: "MOM_UPLOAD_IMAGE",
  MOM_DELETE_IMAGE: "MOM_DELETE_IMAGE",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export interface AuditFiltersInput {
  userIds?: string[];
  actions?: string[];
  phaseIds?: string[];
  dateFrom?: string | null;
  dateTo?: string | null;
}

export type AuditLogWithUser = Prisma.AuditLogGetPayload<{
  include: { user: { select: { id: true; name: true; role: true } } };
}>;

export type AuditReferenceRecord = {
  /// Nullable sejak AuditLog generic (R3): baris MASTER_DATA/BQ tidak punya
  /// user StudioFlow.
  user_id: string | null;
  actor_id: string | null;
  phase_id: string | null;
  entity_type: string;
  entity_id: string;
  metadata_json: Prisma.JsonValue | null;
};
