"use client";

import { useId, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  DndContext,
  KeyboardSensor,
  PointerSensor,
  closestCenter,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  SortableContext,
  arrayMove,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { ArrowRight, GripVertical, LockKeyhole, Merge, RefreshCw } from "lucide-react";
import {
  normalizeAllSketchupMaterialCodesAction,
  normalizeSketchupMaterialCodesAction,
  queueSketchupMaterialMergeAction,
  setSketchupMaterialReservedAction,
} from "../actions/sketchup-actions";

type MaterialItem = {
  id: string;
  code: string;
  uuid: string;
  brand: string | null;
  type: string | null;
  is_reserved: boolean;
};

type MaterialCodeManagerProps = {
  projectId: string;
  sketchupProjectId: string;
  materials: MaterialItem[];
  pendingActionCount: number;
};

type ParsedMaterialCode = {
  prefix: string;
  number: number;
};

const MATERIAL_CODE_PATTERN = /^([A-Z][A-Z0-9]*)-(\d+)$/;

function parseMaterialCode(code: string): ParsedMaterialCode | null {
  const match = MATERIAL_CODE_PATTERN.exec(code.trim().toUpperCase());
  if (!match) return null;

  const number = Number(match[2]);
  if (!Number.isSafeInteger(number) || number < 1) return null;

  return { prefix: match[1], number };
}

function getActionError(result: { error?: string }) {
  return result.error || "The material code change could not be queued.";
}

function SortableMaterialRow({
  material,
  disabled,
  onToggleReserved,
}: {
  material: MaterialItem;
  disabled: boolean;
  onToggleReserved: (material: MaterialItem) => void;
}) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: material.id, disabled: disabled || material.is_reserved });
  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.55 : 1,
  };

  return (
    <li
      ref={setNodeRef}
      style={style}
      className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-[var(--ui-border-subtle,rgb(241_245_249))] bg-white px-[var(--ui-section-px)] py-3 last:border-b-0"
    >
      <button
        type="button"
        className="cursor-grab touch-none text-slate-400 hover:text-slate-700 disabled:cursor-not-allowed disabled:text-slate-300"
        disabled={disabled || material.is_reserved}
        aria-label={`Reorder ${material.code}`}
        {...attributes}
        {...listeners}
      >
        <GripVertical className="h-4 w-4" />
      </button>

      <div className="min-w-0">
        <p className="font-mono text-sm font-semibold text-slate-900">{material.code}</p>
        <p className="mt-0.5 truncate text-xs text-slate-500">
          {[material.brand, material.type].filter(Boolean).join(" / ") || "No material details"}
        </p>
      </div>

      <button
        type="button"
        disabled={disabled}
        onClick={() => onToggleReserved(material)}
        className={`inline-flex items-center gap-1.5 rounded-[var(--ui-radius-action,calc(var(--ui-radius-card,0.75rem)*0.33))] border px-2.5 py-1.5 text-xs font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-60 ${
          material.is_reserved
            ? "border-amber-200 bg-amber-50 text-amber-800 hover:bg-amber-100"
            : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
        }`}
      >
        <LockKeyhole className="h-3.5 w-3.5" />
        {material.is_reserved ? "Reserved" : "Reserve"}
      </button>
    </li>
  );
}

export function MaterialCodeManager({
  projectId,
  sketchupProjectId,
  materials,
  pendingActionCount,
}: MaterialCodeManagerProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [activePrefix, setActivePrefix] = useState("");
  const [localOrders, setLocalOrders] = useState<Record<string, string[]>>({});
  const [sourceMaterialId, setSourceMaterialId] = useState("");
  const [targetMaterialId, setTargetMaterialId] = useState("");
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 6 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
  );
  // dnd-kit derives its aria-describedby ids from an internal auto-increment
  // counter by default, which drifts between the server render and the
  // client hydration pass (each mounts the counter independently) and
  // throws a hydration mismatch. Passing a stable id here — generated by
  // React's own useId(), which IS guaranteed to match between server and
  // client — makes dnd-kit derive its aria ids from this instead.
  const dndContextId = useId();

  const materialsByPrefix = new Map<string, MaterialItem[]>();
  for (const material of materials) {
    const parsedCode = parseMaterialCode(material.code);
    if (!parsedCode) continue;

    const group = materialsByPrefix.get(parsedCode.prefix) || [];
    group.push(material);
    materialsByPrefix.set(parsedCode.prefix, group);
  }

  const prefixes = Array.from(materialsByPrefix.keys()).sort();
  const selectedPrefix = prefixes.includes(activePrefix) ? activePrefix : (prefixes[0] || "");
  const baseMaterials = (materialsByPrefix.get(selectedPrefix) || []).sort((left, right) => {
    const leftCode = parseMaterialCode(left.code)!;
    const rightCode = parseMaterialCode(right.code)!;
    return leftCode.number - rightCode.number || left.code.localeCompare(right.code);
  });
  const materialById = new Map(baseMaterials.map((material) => [material.id, material]));
  const requestedOrder = localOrders[selectedPrefix];
  const orderedMaterials = requestedOrder && requestedOrder.length === baseMaterials.length
    ? requestedOrder.map((id) => materialById.get(id)).filter((material): material is MaterialItem => Boolean(material))
    : baseMaterials;
  const isLocked = isPending || pendingActionCount > 0;

  const setPrefix = (prefix: string) => {
    setActivePrefix(prefix);
    setSourceMaterialId("");
    setTargetMaterialId("");
  };

  const handleDragEnd = ({ active, over }: DragEndEvent) => {
    if (isLocked || !over || active.id === over.id) return;

    const oldIndex = orderedMaterials.findIndex((material) => material.id === active.id);
    const newIndex = orderedMaterials.findIndex((material) => material.id === over.id);
    if (oldIndex < 0 || newIndex < 0) return;

    const movedMaterials = arrayMove(orderedMaterials, oldIndex, newIndex);
    setLocalOrders((current) => ({
      ...current,
      [selectedPrefix]: movedMaterials.map((material) => material.id),
    }));
  };

  const handleToggleReserved = (material: MaterialItem) => {
    startTransition(async () => {
      const result = await setSketchupMaterialReservedAction({
        projectId,
        sketchupProjectId,
        materialId: material.id,
        isReserved: !material.is_reserved,
      });

      if (result.success) {
        toast.success(material.is_reserved ? `${material.code} is no longer reserved.` : `${material.code} is reserved.`);
        router.refresh();
        return;
      }

      toast.error(getActionError(result));
    });
  };

  const handleNormalize = () => {
    if (!selectedPrefix || orderedMaterials.length === 0) return;

    startTransition(async () => {
      const result = await normalizeSketchupMaterialCodesAction({
        projectId,
        sketchupProjectId,
        prefix: selectedPrefix,
        orderedMaterialIds: orderedMaterials.map((material) => material.id),
      });

      if (result.success) {
        toast.success(
          result.queued > 0
            ? `${result.queued} material changes are queued for the next SketchUp sync.`
            : "This material group is already normalized."
        );
        router.refresh();
        return;
      }

      toast.error(getActionError(result));
    });
  };

  const handleNormalizeAll = () => {
    startTransition(async () => {
      const result = await normalizeAllSketchupMaterialCodesAction({
        projectId,
        sketchupProjectId,
      });

      if (result.success) {
        const messages = [
          result.queued > 0
            ? `${result.queued} material changes across all groups are queued for the next SketchUp sync.`
            : "All code groups are already normalized.",
        ];
        if (result.skipped && result.skipped.length > 0) {
          messages.push(`Skipped (duplicate numbers): ${result.skipped.join(", ")}.`);
        }
        toast.success(messages.join(" "));
        router.refresh();
        return;
      }

      toast.error(getActionError(result));
    });
  };

  const handleMerge = () => {
    if (!sourceMaterialId || !targetMaterialId) {
      toast.error("Choose the source and target material first.");
      return;
    }

    startTransition(async () => {
      const result = await queueSketchupMaterialMergeAction({
        projectId,
        sketchupProjectId,
        sourceMaterialId,
        targetMaterialId,
      });

      if (result.success) {
        toast.success("Merge is queued and will run in the next SketchUp sync.");
        setSourceMaterialId("");
        setTargetMaterialId("");
        router.refresh();
        return;
      }

      toast.error(getActionError(result));
    });
  };

  return (
    <section className="overflow-hidden border border-slate-200 bg-white shadow-[var(--ui-shadow-card)] rounded-[var(--ui-radius-card,0.75rem)]">
      <div className="flex flex-col gap-4 border-b border-slate-200 bg-slate-50/60 px-[var(--ui-section-px)] py-[var(--ui-section-py)] lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="font-sans text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">SketchUp Material Codes</p>
          <h2 className="mt-1 font-serif text-xl font-bold tracking-tight text-slate-950">Code Manager</h2>
          <p className="mt-1 max-w-2xl font-sans text-sm text-slate-600">
            Drag material to define its next number, reserve a number that must not move, or merge duplicate finishes. All changes are applied by the next full SketchUp sync.
          </p>
        </div>
        <div className="flex shrink-0 items-center gap-3">
          <button
            type="button"
            onClick={handleNormalizeAll}
            disabled={isLocked || prefixes.length === 0}
            title="Renumber every code group at once so each is gap-free (reserved codes stay fixed)."
            className="inline-flex items-center gap-2 rounded-[var(--ui-radius-action,calc(var(--ui-radius-card,0.75rem)*0.33))] bg-slate-900 px-3 py-2 text-xs font-semibold text-white transition-colors hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
          >
            <RefreshCw className="h-3.5 w-3.5" />
            Normalize All Groups
          </button>
          <div className="inline-flex items-center rounded-[var(--ui-radius-pill)] border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-600">
            {prefixes.length} code group{prefixes.length === 1 ? "" : "s"}
          </div>
        </div>
      </div>

      {pendingActionCount > 0 && (
        <div className="flex items-start gap-3 border-b border-amber-200 bg-amber-50 px-[var(--ui-section-px)] py-3 text-sm text-amber-900">
          <RefreshCw className="mt-0.5 h-4 w-4 shrink-0" />
          <p>
            {pendingActionCount} material change{pendingActionCount === 1 ? " is" : "s are"} waiting for SketchUp sync. New code changes are locked until the plugin confirms them.
          </p>
        </div>
      )}

      {prefixes.length === 0 ? (
        <div className="px-[var(--ui-section-px)] py-10 text-center">
          <p className="font-serif text-lg font-bold text-slate-900">No valid material codes yet</p>
          <p className="mt-1 text-sm text-slate-500">Sync the model after assigning registered material codes in the BerkahStudio plugin.</p>
        </div>
      ) : (
        <div className="grid gap-6 p-[var(--ui-section-px)] xl:grid-cols-[minmax(0,1fr)_minmax(320px,0.72fr)]">
          <div>
            <div className="mb-4 flex flex-wrap gap-2">
              {prefixes.map((prefix) => (
                <button
                  key={prefix}
                  type="button"
                  onClick={() => setPrefix(prefix)}
                  className={`rounded-[var(--ui-radius-action,calc(var(--ui-radius-card,0.75rem)*0.33))] border px-3 py-1.5 font-mono text-sm font-semibold transition-colors ${
                    selectedPrefix === prefix
                      ? "border-slate-900 bg-slate-900 text-white"
                      : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
                  }`}
                >
                  {prefix}
                </button>
              ))}
            </div>

            <div className="overflow-hidden rounded-[var(--ui-radius-control,calc(var(--ui-radius-card,0.75rem)*0.66))] border border-slate-200">
              <div className="flex items-center justify-between bg-slate-50 px-[var(--ui-section-px)] py-3">
                <div>
                  <p className="font-sans text-sm font-semibold text-slate-900">{selectedPrefix} sequence</p>
                  <p className="mt-0.5 text-xs text-slate-500">Reserved codes stay fixed and are skipped during normalization.</p>
                </div>
                <button
                  type="button"
                  onClick={handleNormalize}
                  disabled={isLocked}
                  className="inline-flex items-center gap-2 rounded-[var(--ui-radius-action,calc(var(--ui-radius-card,0.75rem)*0.33))] bg-slate-900 px-3 py-2 text-xs font-semibold text-white transition-colors hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <RefreshCw className="h-3.5 w-3.5" />
                  Normalize
                </button>
              </div>

              <DndContext id={dndContextId} sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
                <SortableContext items={orderedMaterials.map((material) => material.id)} strategy={verticalListSortingStrategy}>
                  <ul>
                    {orderedMaterials.map((material) => (
                      <SortableMaterialRow
                        key={material.id}
                        material={material}
                        disabled={isLocked}
                        onToggleReserved={handleToggleReserved}
                      />
                    ))}
                  </ul>
                </SortableContext>
              </DndContext>
            </div>
          </div>

          <aside className="h-fit rounded-[var(--ui-radius-control,calc(var(--ui-radius-card,0.75rem)*0.66))] border border-slate-200 bg-slate-50/70 p-[var(--ui-section-px)]">
            <div className="flex items-center gap-2">
              <Merge className="h-4 w-4 text-slate-500" />
              <h3 className="font-sans text-sm font-semibold text-slate-900">Merge duplicate material</h3>
            </div>
            <p className="mt-1 text-xs leading-5 text-slate-500">
              The source material is removed and its faces use the target material. Both must be valid {selectedPrefix} codes.
            </p>

            <label className="mt-5 block text-xs font-medium text-slate-700" htmlFor={`merge-source-${selectedPrefix}`}>
              Source to remove
            </label>
            <select
              id={`merge-source-${selectedPrefix}`}
              value={sourceMaterialId}
              disabled={isLocked}
              onChange={(event) => setSourceMaterialId(event.target.value)}
              className="mt-1.5 w-full rounded-[var(--ui-radius-action,calc(var(--ui-radius-card,0.75rem)*0.33))] border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-slate-400 disabled:cursor-not-allowed disabled:opacity-60"
            >
              <option value="">Choose material</option>
              {orderedMaterials.map((material) => (
                <option key={material.id} value={material.id} disabled={material.is_reserved}>
                  {material.code}{material.is_reserved ? " (reserved)" : ""}
                </option>
              ))}
            </select>

            <div className="flex justify-center py-2 text-slate-400"><ArrowRight className="h-4 w-4 rotate-90" /></div>

            <label className="block text-xs font-medium text-slate-700" htmlFor={`merge-target-${selectedPrefix}`}>
              Target to keep
            </label>
            <select
              id={`merge-target-${selectedPrefix}`}
              value={targetMaterialId}
              disabled={isLocked}
              onChange={(event) => setTargetMaterialId(event.target.value)}
              className="mt-1.5 w-full rounded-[var(--ui-radius-action,calc(var(--ui-radius-card,0.75rem)*0.33))] border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-slate-400 disabled:cursor-not-allowed disabled:opacity-60"
            >
              <option value="">Choose material</option>
              {orderedMaterials.map((material) => (
                <option key={material.id} value={material.id} disabled={material.id === sourceMaterialId}>
                  {material.code}{material.is_reserved ? " (reserved)" : ""}
                </option>
              ))}
            </select>

            <button
              type="button"
              onClick={handleMerge}
              disabled={isLocked || !sourceMaterialId || !targetMaterialId}
              className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-[var(--ui-radius-action,calc(var(--ui-radius-card,0.75rem)*0.33))] border border-slate-900 bg-white px-3 py-2.5 text-sm font-semibold text-slate-900 transition-colors hover:bg-slate-900 hover:text-white disabled:cursor-not-allowed disabled:border-slate-200 disabled:text-slate-400 disabled:hover:bg-white"
            >
              <Merge className="h-4 w-4" />
              Queue merge
            </button>
          </aside>
        </div>
      )}
    </section>
  );
}
