-- C-SISA-5: named personal filters for the Tasks feed.
-- query_json is deliberately structured JSON (status/priority/assignee/due),
-- not a text DSL. UUID values are generated by Prisma, matching existing
-- StudioFlow tables whose String IDs are stored as TEXT.
CREATE TABLE "studioflow"."ChecklistFilterView" (
  "id"         TEXT NOT NULL,
  "owner_id"   TEXT NOT NULL,
  "name"       TEXT NOT NULL,
  "query_json" JSONB NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "ChecklistFilterView_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "ChecklistFilterView_owner_id_name_key"
  ON "studioflow"."ChecklistFilterView"("owner_id", "name");

CREATE INDEX "ChecklistFilterView_owner_id_created_at_idx"
  ON "studioflow"."ChecklistFilterView"("owner_id", "created_at");

ALTER TABLE "studioflow"."ChecklistFilterView"
  ADD CONSTRAINT "ChecklistFilterView_owner_id_fkey"
  FOREIGN KEY ("owner_id") REFERENCES "studioflow"."User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
