/**
 * Granular Permissions for the StudioFlow system.
 * Centralized here to ensure a single source of truth for access control.
 */
export enum PERMISSION {
  // Project Permissions (8)
  PROJECT_CREATE = "PROJECT_CREATE",
  PROJECT_DELETE = "PROJECT_DELETE",
  PROJECT_EDIT_METADATA = "PROJECT_EDIT_METADATA",
  PROJECT_EDIT_PRIORITY = "PROJECT_EDIT_PRIORITY",
  PROJECT_VIEW_AUDIT = "PROJECT_VIEW_AUDIT",
  PROJECT_SYNC_CHECKLIST = "PROJECT_SYNC_CHECKLIST",
  PROJECT_FORCE_SYNC = "PROJECT_FORCE_SYNC",
  PROJECT_EXPORT_PDF = "PROJECT_EXPORT_PDF",

  // Phase Permissions (12)
  PHASE_ACTIVATE = "PHASE_ACTIVATE",
  PHASE_SUBMIT_REVIEW = "PHASE_SUBMIT_REVIEW",
  PHASE_APPROVE_INTERNAL = "PHASE_APPROVE_INTERNAL",
  PHASE_APPROVE_CLIENT = "PHASE_APPROVE_CLIENT",
  PHASE_REJECT = "PHASE_REJECT",
  PHASE_REOPEN = "PHASE_REOPEN",
  PHASE_OVERRIDE = "PHASE_OVERRIDE",
  PHASE_MUTATE_CONTENT = "PHASE_MUTATE_CONTENT",
  PHASE_UPLOAD_FILE = "PHASE_UPLOAD_FILE",
  PHASE_DELETE_FILE = "PHASE_DELETE_FILE",
  PHASE_MANAGE_CD = "PHASE_MANAGE_CD",
  PHASE_MANAGE_TIMELINE = "PHASE_MANAGE_TIMELINE",

  // Scheduled Fixtures (Plugin) (7)
  PLUGIN_SCHEDULE_ADD = "PLUGIN_SCHEDULE_ADD",
  PLUGIN_SCHEDULE_EDIT = "PLUGIN_SCHEDULE_EDIT",
  PLUGIN_SCHEDULE_DELETE = "PLUGIN_SCHEDULE_DELETE",
  PLUGIN_SCHEDULE_APPROVE = "PLUGIN_SCHEDULE_APPROVE",
  PLUGIN_SCHEDULE_EXPORT = "PLUGIN_SCHEDULE_EXPORT",
  PLUGIN_SCHEDULE_ASSIGN = "PLUGIN_SCHEDULE_ASSIGN",
  PLUGIN_SCHEDULE_VIEW = "PLUGIN_SCHEDULE_VIEW",

  // Library Permissions (12)
  LIBRARY_VIEW = "LIBRARY_VIEW",
  LIBRARY_CREATE_ITEM = "LIBRARY_CREATE_ITEM",
  LIBRARY_EDIT_ITEM = "LIBRARY_EDIT_ITEM",
  LIBRARY_DELETE_ITEM = "LIBRARY_DELETE_ITEM",
  LIBRARY_MANAGE_VENDORS = "LIBRARY_MANAGE_VENDORS",
  LIBRARY_MANAGE_BRANDS = "LIBRARY_MANAGE_BRANDS",
  LIBRARY_MANAGE_SAMPLES = "LIBRARY_MANAGE_SAMPLES",
  LIBRARY_REQUEST_MATERIAL = "LIBRARY_REQUEST_MATERIAL",
  LIBRARY_PROCESS_REQUEST = "LIBRARY_PROCESS_REQUEST",
  LIBRARY_MARK_RECEIVED = "LIBRARY_MARK_RECEIVED",
  LIBRARY_EXPORT_LIST = "LIBRARY_EXPORT_LIST",
  LIBRARY_ADMIN_OVERRIDE = "LIBRARY_ADMIN_OVERRIDE",

  // System Permissions
  SYSTEM_CONFIG_EDIT = "SYSTEM_CONFIG_EDIT",
}
