import { Role } from "@/generated/prisma";
import { PERMISSION } from "./constants";

/**
 * Static mapping of Roles to Permissions.
 */
export const ROLE_PERMISSIONS: Record<Role, PERMISSION[]> = {
  ADMIN: Object.values(PERMISSION),
  STAFF: [
    PERMISSION.PROJECT_VIEW_AUDIT,
    PERMISSION.PLUGIN_SCHEDULE_VIEW,
    PERMISSION.LIBRARY_VIEW,
    PERMISSION.LIBRARY_EXPORT_LIST,
  ],
  DIC: [
    PERMISSION.PROJECT_EDIT_METADATA,
    PERMISSION.PROJECT_SYNC_CHECKLIST,
    PERMISSION.PROJECT_EXPORT_PDF,
    PERMISSION.PHASE_ACTIVATE,
    PERMISSION.PHASE_SUBMIT_REVIEW,
    PERMISSION.PHASE_APPROVE_INTERNAL,
    PERMISSION.PHASE_REOPEN,
    PERMISSION.PHASE_OVERRIDE,
    PERMISSION.PHASE_MUTATE_CONTENT,
    PERMISSION.PHASE_UPLOAD_FILE,
    PERMISSION.PHASE_DELETE_FILE,
    PERMISSION.PLUGIN_SCHEDULE_ADD,
    PERMISSION.PLUGIN_SCHEDULE_EDIT,
    PERMISSION.PLUGIN_SCHEDULE_DELETE,
    PERMISSION.PLUGIN_SCHEDULE_VIEW,
    PERMISSION.LIBRARY_VIEW,
    PERMISSION.LIBRARY_REQUEST_MATERIAL,
  ],
  DRIC: [
    PERMISSION.PHASE_MUTATE_CONTENT,
    PERMISSION.PHASE_UPLOAD_FILE,
    PERMISSION.PLUGIN_SCHEDULE_ADD,
    PERMISSION.PLUGIN_SCHEDULE_EDIT,
    PERMISSION.PLUGIN_SCHEDULE_VIEW,
    PERMISSION.LIBRARY_VIEW,
    PERMISSION.LIBRARY_REQUEST_MATERIAL,
  ],
};
