export {
  CONTAINER_MAX_WIDTH,
  UI_ENGINE_CONTAINER_MAX_WIDTH,
  UI_ENGINE_CENTERED_CONTAINER_CLASS,
  UI_ENGINE_SPACING_SECTION_PX,
  UI_ENGINE_SPACING_SECTION_PY,
  UI_ENGINE_PAGE_SHELL_CLASS,
  UI_ENGINE_RADIUS_CARD,
  UI_ENGINE_RADIUS_CONTROL,
  UI_ENGINE_RADIUS_ACTION,
  UI_ENGINE_RADIUS_BUTTON,
  UI_ENGINE_RADIUS_INPUT,
} from "./index";

export const UI_ENGINE_RADIUS_IMAGE = "rounded-[var(--ui-radius-control)]";
